# filename: sap-drc-notebook-display.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from IPython.display import display, HTML
import numpy as np
import requests
from dataclasses import dataclass, field

JEV_API_KEY  = "sk_18ztYamfADXN7NC2rPMo-f-XxI-d68F57XT-XBG4bo0"
JEV_ENDPOINT = "https://jevaimodel.net/v1/systemone"
JEV_MODEL    = "typesafe/jev-1.13"

# ─────────────────────────────────────────────
# KNOWLEDGE BASE + VECTOR ENGINE (unchanged)
# ─────────────────────────────────────────────

ERROR_LIBRARY = {
    "err_001": {"text": "Mandatory buyer electronic address or VAT identifier is missing or incorrectly formatted.", "error_category": "buyer_address",    "resolution_type": "manual_correction"},
    "err_002": {"text": "Supplier postal address is incomplete — street name, city, or postal code tag is missing.", "error_category": "supplier_address",  "resolution_type": "manual_correction"},
    "err_003": {"text": "Tax identifier syntax is invalid — VAT number does not match the required country format.", "error_category": "tax_identifier",    "resolution_type": "consultant_escalation"},
    "err_004": {"text": "Invoice total amount does not match the sum of line item amounts — arithmetic mismatch.",   "error_category": "calculation_error", "resolution_type": "auto_fix"},
    "err_005": {"text": "Tax category code is missing or not valid for the specified invoice type under ZATCA.",     "error_category": "tax_category",      "resolution_type": "consultant_escalation"},
    "err_006": {"text": "Invoice issue date is missing or not in the required ISO 8601 format (YYYY-MM-DD).",       "error_category": "date_format",       "resolution_type": "auto_fix"},
    "err_007": {"text": "Mandatory seller VAT registration number (BT-31) is absent from the invoice header.",     "error_category": "tax_identifier",    "resolution_type": "consultant_escalation"},
    "err_008": {"text": "Currency code is missing or does not match an ISO 4217 standard code.",                   "error_category": "currency",          "resolution_type": "manual_correction"},
    "err_009": {"text": "Payment means code is invalid or not supported for this e-invoicing compliance region.",  "error_category": "payment",           "resolution_type": "manual_correction"},
    "err_010": {"text": "Line item unit price is zero or negative — likely a data entry or mapping error.",        "error_category": "calculation_error", "resolution_type": "auto_fix"},
}

KEYWORD_SIGNALS = {
    "address":     ["address", "postal", "street", "city", "buyer", "supplier", "electronic", "missing"],
    "tax":         ["tax", "vat", "taxid", "identifier", "registration", "syntax", "format", "zatca"],
    "calculation": ["total", "amount", "sum", "line item", "mismatch", "zero", "negative", "arithmetic"],
    "compliance":  ["code", "currency", "payment", "category", "iso", "mandatory", "invalid", "date"],
}

DECISION_COLORS = {
    "AUTO_FIX":              "#86BC25",
    "MANUAL_CORRECTION":     "#E8A317",
    "CONSULTANT_ESCALATION": "#DA291C",
    "NEEDS_MORE_INFO":       "#888888",
}

DECISION_ICONS = {
    "AUTO_FIX":              "&#10003;",
    "MANUAL_CORRECTION":     "&#9888;",
    "CONSULTANT_ESCALATION": "&#128680;",
    "NEEDS_MORE_INFO":       "&#63;",
}

def get_embedding(text: str) -> np.ndarray:
    text_lower = text.lower()
    scores = np.zeros(4)
    for i, kws in enumerate(KEYWORD_SIGNALS.values()):
        for kw in kws:
            if kw in text_lower:
                scores[i] += 0.30
    scores = np.clip(scores + 0.05, 0, 1.0)
    norm = np.linalg.norm(scores)
    return scores / norm if norm > 0 else scores

def get_keyword_hits(text: str) -> dict:
    text_lower = text.lower()
    return {
        dim: [kw for kw in kws if kw in text_lower]
        for dim, kws in KEYWORD_SIGNALS.items()
        if any(kw in text_lower for kw in kws)
    }

def cosine_similarity(v1: np.ndarray, v2: np.ndarray) -> float:
    denom = np.linalg.norm(v1) * np.linalg.norm(v2)
    return float(np.dot(v1, v2) / denom) if denom > 0 else 0.0

def semantic_search(error_input: str) -> list:
    query_vec = get_embedding(error_input)
    results = []
    for err_id, err_data in ERROR_LIBRARY.items():
        score = cosine_similarity(query_vec, get_embedding(err_data["text"]))
        results.append({"err_id": err_id, "score": score, **err_data})
    return sorted(results, key=lambda x: x["score"], reverse=True)

# ─────────────────────────────────────────────
# JEV API
# ─────────────────────────────────────────────

@dataclass
class JevResult:
    decision: str
    confidence: float
    error_category: str
    matched_err_id: str
    human_readable_match: str
    is_critical: float
    match_quality: float

def call_jev(raw_error: str, best: dict) -> JevResult:
    payload = {
        "model": JEV_MODEL,
        "state": f'Raw SAP DRC Error: "{raw_error}"\nClosest known error [{best["err_id"]}]: "{best["text"]}"',
        "questions": {
            "routing_decision": {
                "type": "choice",
                "instructions": "What is the correct resolution action for this SAP DRC error?",
                "criteria": {
                    "AUTO_FIX":             "Formatting or calculation issue correctable automatically",
                    "MANUAL_CORRECTION":    "Requires human review and correction",
                    "CONSULTANT_ESCALATION":"Involves tax/VAT/compliance rules needing expert review",
                    "NEEDS_MORE_INFO":      "Ambiguous — needs additional context"
                }
            },
            "is_compliance_critical": {"type": "noul", "instructions": "This error would cause invoice rejection by the tax authority."},
            "is_good_match":          {"type": "noul", "instructions": "The knowledge base description is a good translation of the raw SAP error."}
        }
    }
    try:
        r = requests.post(JEV_ENDPOINT, json=payload, headers={"Authorization": f"Bearer {JEV_API_KEY}", "Content-Type": "application/json"})
        r.raise_for_status()
        answers  = r.json().get("data", {}).get("result", {}).get("answers", {})
        routing  = answers.get("routing_decision", {})
        return JevResult(
            decision=routing.get("choice", "NEEDS_MORE_INFO"),
            confidence=round(routing.get("confidence", 0.0), 3),
            error_category=best.get("error_category", "unknown"),
            matched_err_id=best["err_id"],
            human_readable_match=best["text"],
            is_critical=round(answers.get("is_compliance_critical", {}).get("noul", 0.0), 3),
            match_quality=round(answers.get("is_good_match", {}).get("noul", 0.0), 3),
        )
    except Exception as e:
        return JevResult("NEEDS_MORE_INFO", 0.0, "unknown", "none", str(e), 0.0, 0.0)

# ─────────────────────────────────────────────
# HTML RENDERER — works in SingleStore notebook
# ─────────────────────────────────────────────

def render_result(raw_error: str):
    candidates = semantic_search(raw_error)
    best       = candidates[0]
    result     = call_jev(raw_error, best)
    hits       = get_keyword_hits(raw_error)
    vec        = get_embedding(raw_error)
    dims       = list(KEYWORD_SIGNALS.keys())
    color      = DECISION_COLORS.get(result.decision, "#888")
    icon       = DECISION_ICONS.get(result.decision, "?")

    # Similarity bars
    bars_html = ""
    for entry in candidates[:5]:
        pct        = int(entry["score"] * 100)
        bar_color  = "#86BC25" if entry["err_id"] == best["err_id"] else "#ddd"
        bars_html += f"""
        <div style="margin-bottom:8px;">
            <div style="font-size:12px;color:#555;">[{entry['err_id']}] {entry['text'][:60]}...</div>
            <div style="display:flex;align-items:center;gap:8px;">
                <div style="flex:1;background:#eee;border-radius:4px;height:10px;">
                    <div style="background:{bar_color};width:{pct}%;height:10px;border-radius:4px;"></div>
                </div>
                <span style="font-size:12px;color:#888;width:40px;">{entry['score']:.3f}</span>
            </div>
        </div>"""

    # Keyword hits
    kw_html = ""
    for dim, words in hits.items():
        kw_html += f'<span style="background:#f0f8e8;border:1px solid #86BC25;border-radius:4px;padding:2px 8px;margin:2px;font-size:12px;display:inline-block;"><b>{dim}</b>: {", ".join(words)}</span>'

    # Vector dims
    vec_html = "".join([f"""
        <div style="text-align:center;background:#f5f5f5;border-radius:6px;padding:8px 12px;">
            <div style="font-size:11px;color:#888;text-transform:uppercase;">{dims[i]}</div>
            <div style="font-size:18px;font-weight:700;color:#282728;">{vec[i]:.3f}</div>
        </div>""" for i in range(4)])

    # Critical banner
    if result.is_critical >= 0.8:
        banner = f'<div style="background:#DA291C;color:white;padding:10px 16px;border-radius:6px;font-weight:600;">Invoice rejection risk — resolve immediately!</div>'
    elif result.is_critical >= 0.5:
        banner = f'<div style="background:#E8A317;color:white;padding:10px 16px;border-radius:6px;font-weight:600;">Compliance risk — review recommended.</div>'
    else:
        banner = f'<div style="background:#86BC25;color:white;padding:10px 16px;border-radius:6px;font-weight:600;">Low compliance risk — standard processing applies.</div>'

    html = f"""
    <div style="font-family:Arial,sans-serif;max-width:900px;margin:auto;">

        <!-- Header -->
        <div style="background:#282728;padding:16px 24px;border-radius:8px;margin-bottom:16px;">
            <span style="color:#86BC25;font-size:20px;font-weight:800;">SAP DRC</span>
            <span style="color:white;font-size:20px;font-weight:300;"> | Error Translation & Routing</span>
            <div style="color:#aaa;font-size:12px;margin-top:4px;">Powered by RAG + Jev AI</div>
        </div>

        <!-- Raw Error -->
        <div style="background:#fff;border-left:5px solid #282728;border-radius:6px;padding:14px 18px;margin-bottom:12px;box-shadow:0 1px 3px rgba(0,0,0,0.08);">
            <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;">Raw SAP Error Input</div>
            <div style="font-family:monospace;font-size:14px;color:#1a1a1a;margin-top:4px;">{raw_error}</div>
        </div>

        <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;">

            <!-- LEFT: Vector Process -->
            <div>
                <div style="font-weight:700;margin-bottom:8px;color:#282728;">Vector Translation Process</div>

                <div style="background:#fff;border-radius:6px;padding:14px;margin-bottom:10px;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
                    <div style="font-size:11px;color:#888;text-transform:uppercase;margin-bottom:6px;">Step 1 — Keywords Detected</div>
                    {kw_html if kw_html else '<span style="color:#aaa;font-size:12px;">No strong keyword signals found</span>'}
                </div>

                <div style="background:#fff;border-radius:6px;padding:14px;margin-bottom:10px;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
                    <div style="font-size:11px;color:#888;text-transform:uppercase;margin-bottom:8px;">Step 2 — Input Vector</div>
                    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px;">{vec_html}</div>
                </div>

                <div style="background:#fff;border-radius:6px;padding:14px;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
                    <div style="font-size:11px;color:#888;text-transform:uppercase;margin-bottom:8px;">Step 3 — Similarity Scores</div>
                    {bars_html}
                </div>
            </div>

            <!-- RIGHT: Results -->
            <div>
                <div style="font-weight:700;margin-bottom:8px;color:#282728;">Translation & Routing Result</div>

                <div style="background:#fff;border-left:5px solid #86BC25;border-radius:6px;padding:14px;margin-bottom:10px;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
                    <div style="font-size:11px;color:#888;text-transform:uppercase;">Human-Readable Translation</div>
                    <div style="font-size:15px;font-weight:600;color:#1a1a1a;margin-top:6px;">{result.human_readable_match}</div>
                    <div style="margin-top:8px;font-size:12px;color:#888;">
                        Category: <b>{result.error_category.replace("_"," ").title()}</b>
                        &nbsp;|&nbsp; Matched: <b>{result.matched_err_id}</b>
                    </div>
                </div>

                <div style="background:#fff;border-left:5px solid {color};border-radius:6px;padding:14px;margin-bottom:10px;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
                    <div style="font-size:11px;color:#888;text-transform:uppercase;">Jev Routing Decision</div>
                    <div style="font-size:22px;font-weight:800;color:{color};margin-top:6px;">{icon} {result.decision.replace("_"," ")}</div>
                </div>

                <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:10px;">
                    <div style="background:#fff;border-radius:6px;padding:12px;text-align:center;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
                        <div style="font-size:11px;color:#888;">Confidence</div>
                        <div style="font-size:22px;font-weight:800;color:#282728;">{int(result.confidence*100)}%</div>
                    </div>
                    <div style="background:#fff;border-radius:6px;padding:12px;text-align:center;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
                        <div style="font-size:11px;color:#888;">Compliance Risk</div>
                        <div style="font-size:22px;font-weight:800;color:#282728;">{int(result.is_critical*100)}%</div>
                    </div>
                    <div style="background:#fff;border-radius:6px;padding:12px;text-align:center;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
                        <div style="font-size:11px;color:#888;">Match Quality</div>
                        <div style="font-size:22px;font-weight:800;color:#282728;">{int(result.match_quality*100)}%</div>
                    </div>
                </div>

                {banner}
            </div>
        </div>
    </div>
    """
    display(HTML(html))

# ─────────────────────────────────────────────
# RUN — one cell per error or loop all
# ─────────────────────────────────────────────

test_errors = [
    "BR-KSA-05: Buyer electronic address is missing or invalid, TaxID format syntax error",
    "BR-CO-04: Invoice total VAT amount is not equal to the sum of tax amounts per line",
    "BT-31: Seller VAT identifier missing from invoice header",
    "BR-KSA-26: Tax category code Z is not allowed for this supply type under ZATCA Phase 2",
    "UBL-SR-01: Invoice issue date element is absent or malformed",
]

for error in test_errors:
    render_result(error)
